version: "3.8"
services:
        sonarqube:
                depends_on:
                        - db
                image: sonarqube:7.8-community
                ports:
                        - 0.0.0.0:9000:9000
                        - 3306:3306
                environment:
                        - SONARQUBE_JDBC_USERNAME=sonar
                        - SONARQUBE_JDBC_PASSWORD=sonar
                        - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance

        db:
                image: mysql
                net: container:sonarqube
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=sonar
                        - MYSQL_DATABASE=sonar
                        - MYSQL_USER=sonar
                        - MYSQL_PASSWORD=sonar
volumes:
        db_data:
